name: Build and Publish Documentation

on:
  push:
    branches: [ main, build ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag build-environment
    - name: Build documentation using Docker
      run: docker run --rm -v ./:/docs build-environment make clean html
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: html
        path: ./build/html
        if-no-files-found: error
        retention-days: 1
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: html
          path: html
      - name: Test
        run: ls -la html
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: ./html
          jekyll: false
        
  clean:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Delete Artifact
      uses: GeekyEggo/delete-artifact@v1.0.0
      with:
        name: html
    
