name: Build and Publish Documentation

on:
  push:
    branches: [ main, build ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag build-environment
    - name: Create build output directory
      run: mkdir -p ./build/html
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: ./build/html
        key: $GITHUB_RUN_ID
    - name: Build documentation using Docker
      run: docker run --rm -v $GITHUB_WORKSPACE:/docs build-environment make clean html

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: ./build/html
        key: $GITHUB_RUN_ID
    - name: Test
      run: ls -la html
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: ./html
        jekyll: false

